---
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ImagePolicy
metadata:
  name: ldap-subscription
  namespace: ldap
spec:
  repositories:
  - name: k8s.gcr.io/*
    policy:
      va:
        enabled: false
  - name: gcr.io/*
    policy:
      va:
        enabled: false
